// Every user-facing string lives here. Sentence case. No em dashes, no exclamation marks, no emoji.
export const copy = {
  brand: 'tacto',
  // sidebar groups: what is live, what the agents are, what is a preview
  nav: { overview: 'Overview', agents: 'Agents', preview: 'Preview agents' },
  productName: 'Procurement cockpit',
  customer: 'MechaForm GmbH',
  cockpit: {
    title: 'Savings agents',
    hardLabel: 'Hard savings identified',
    hardNote: 'Einsparung: below a price the supplier already invoices or grants. One primary case per article, plus payment terms.',
    grossNote: (gross: string) => `Gross sum of all findings ${gross}; cases overlap on articles, so they are not added up.`,
    avoidanceLabel: 'Cost avoidance',
    avoidanceNote: (rate: string) => `Kostenvermeidung: prices above an assumed ${rate} index path from 2024. Not a saving and never added to the headline.`,
    avoidanceOff: 'Price Radar is switched off.',
    exposureReco: 'Einkäufer der Bestellungen und Qualität prüfen den Lieferantenstatus. Die Statustabelle hat kein Datum.',
    switchLabel: (name: string) => `${name} on or off`,
    on: 'On',
    off: 'Off',
    openTasks: (n: number) => `${n} open ${n === 1 ? 'task' : 'tasks'}`,
    switchError: 'Not saved:',
    offNote: 'Switched off: left out of runs and the headline.',
    subtitle: 'Rule agents read the MechaForm order history. Every finding is volume times price gap and ends in a recommendation: who acts, internally or with the supplier. Preview agents sit apart and count in no total.',
    headlineLabel: 'Identified by enabled agents',
    keptApart: 'Kept apart, not savings',
    contractCliff: 'Spend that loses its contract ceiling on 2026-12-31',
    blockedSpend: 'Orders to blocked or phased-out suppliers',
    lastRun: 'Last run',
    notRun: 'Not run for this period',
    runAll: 'Run all agents',
    running: 'Running',
    gross: 'Gross sum of enabled agents',
    dedup: 'One primary case per article, plus terms',
    explain: (name: string) => `Explain ${name}`,
    confidence: (value: string) => `Confidence ${value}, a human judgement of survival after supplier contact`,
    rows: 'flagged rows',
    open: 'Open agent',
    empty: 'No agents enabled. Set VITE_ENABLED_AGENTS to a comma-separated list of case keys.',
    error: 'The database did not answer. Check the Supabase URL and anon key in the environment.',
    loading: 'Loading agents',
  },
  agent: {
    rule: 'Rule',
    evidence: 'Evidence required',
    calculation: 'Calculation',
    action: 'Customer action',
    trigger: 'Trigger',
    register: 'Flagged rows',
    total: 'Total',
    evidenceDrawer: 'Order lines 2026',
    referenced: 'Referenced',
    reference: 'Reference',
    plant: 'Plant',
    netDays: 'Net days',
    spend: 'Spend',
    noSkonto: 'none',
    noLines: 'No order lines in this period.',
    firstLines: (n: number) => `First ${n} lines of the period.`,
    unreferenced: 'No reference',
    close: 'Close',
    page: (n: number, of: number) => `Page ${n} of ${of}`,
    previous: 'Previous',
    next: 'Next',
    perOrder: 'Per order',
    annualVolume: 'Annual volume at top tier',
    yearChart: 'Share of eligible order lines priced above the recorded tier',
    workedExample: 'Worked example',
    run: 'Run agent',
    how: 'How this agent works',
    params: 'Thresholds from mvp_config',
    howClose: 'Hide explanation',
    trend: 'Gap by month',
    findings: 'Findings',
    noRun: 'This agent has not run for the selected period. Run it to see findings.',
  },
  index: {
    samplePill: 'Sample index data',
    feedPill: 'Index feed',
    sampleTitle: 'Index values generated for the MVP, not published statistics.',
    feedTitle: 'Index values from the loaded feed.',
    sampleLead: 'Weights and the 3% tolerance need tuning before any supplier conversation.',
    sampleMore: 'How the index price is built',
    sampleText: 'Every price is escalated from its base year with a cost basket per category (fixed share, material, energy, labour) and compared with what MechaForm paid. The sample series stand in for a real feed (Destatis producer prices, LME metals, wage indices), loaded through the index loader.',
    chartTitle: 'Prices paid against the cost basket, base-year price = 100',
    pickCategory: 'Category',
    categoryLine: (spend: string) => `${spend} of spend in this period on pairs with a base year before it.`,
    paidSeries: 'Prices paid',
    basketSeries: 'Cost basket (index price)',
    basketTitle: 'Cost basket of the category',
    material: 'Material',
    anyMaterial: 'Any',
    component: 'Component',
    weight: 'Weight',
    valueNow: (month: string) => `Index ${month}, Jan 2024 = 100`,
    standsIn: 'Stands in for',
    fixed: 'Fixed share',
    fixedNote: 'Not indexed: margin, overhead, logistics',
    chartNote: 'Both lines are volume-weighted over the pairs of the category. The gap between them is what the basket does not explain; it is a question for the supplier, not yet a saving.',
    indexPrice: 'Index price',
    ceiling: 'Index price + tolerance',
    priceChange: 'Price since base',
    indexChange: 'Basket since base',
    deviation: 'Above index',
    contract: 'Contract',
    actionsTitle: 'Empfehlungen aus diesem Lauf',
    actionsNone: 'Keine Position über dem Toleranzband in dieser Periode.',
    supplierAction: (name: string) => `Preise mit ${name} neu verhandeln`,
    supplierNumbers: (findings: string, articles: string, dev: string, gap: string) => `${findings} Positionen auf ${articles} Artikeln liegen ${dev} über dem Indexpreis; ${gap} über dem Toleranzband.`,
    supplierArticle: (a: string) => `Größte Abweichung: ${a}`,
    supplierContracts: (n: string, c: string) => `${n} Vertragspositionen betroffen, größte: Vertrag ${c}`,
    trainLink: 'Im Verhandlungstrainer üben',
    actionContract: (c: string) => `Preisgespräch zu Vertrag ${c}`,
    actionNoContract: (a: string) => `Preisgespräch zu Artikel ${a}`,
    actionNumbers: (paid: string, idx: string, dev: string, gap: string, vol: string) => `Bezahlt ${paid} gegen Indexpreis ${idx} (${dev} darüber); ${gap} über dem Toleranzband auf ${vol} Stk.`,
    actionAsk: 'Frage an den Lieferanten: welcher Kostenbestandteil trägt die Differenz zum Index?',
    actionOpen: 'Beleg öffnen',
    actionRest: (n: string, gap: string) => `Weitere ${n} Positionen über dem Band, zusammen ${gap}.`,
    verdictNegotiate: 'Verhandlung empfohlen',
    verdictWatch: 'Beobachten',
    verdictNone: 'Kein Handlungsbedarf',
    verdictNegotiateWhy: (above: string, gap: string, n: string) => `Bezahlte Preise ${above} über dem Kostenkorb. ${gap} über dem Toleranzband auf ${n} Positionen.`,
    verdictWatchWhy: (above: string, tol: string) => `${above} über dem Kostenkorb, unter der Toleranz von ${tol}. Im Blick behalten, kein Gespräch nötig.`,
    verdictNoneWhy: 'Der Kostenkorb erklärt die Preisentwicklung dieser Warengruppe. Kein Gespräch nötig.',
    verdictSpread: (paid: string, basket: string) => `Bezahlt ${paid}, Kostenkorb ${basket}, Basisjahr = 100.`,
    previewLabel: 'Preview agent',
    previewNav: 'Preview',
    previewText: 'Checks every order and contract price against a cost index basket for its category. Runs on sample index data, not counted in any total.',
    previewOpen: 'Open Index Guard',
    previewOpenAgent: (name: string) => `Open ${name}`,
    previewFindings: (n: string) => `${n} findings in this period. Values stay out of every total.`,
    previewValue: (v: string, n: string) => `${v} above the index band on ${n} order lines in this period`,
    previewNotRun: 'Not run for this period yet.',
    previewPageText: {
      trainer: 'Practises a negotiation with a supplier on MechaForm data: a language model plays the supplier and a coach. One stored session and one live turn.',
    } as Record<string, string>,
    previewPageName: { trainer: 'Negotiation trainer' } as Record<string, string>,
    previewOpenPage: 'Open',

  },
  charts: {
    contracts: 'Contracts behind the findings',
    contract: 'Contract',
    paid: 'Paid, weighted',
    lines: 'Lines',
    contractsTotal: (n: number) => `Total, ${n} contracts`,
    bridge: 'From Skonto gained to net gain',
    gross: 'Skonto gained at the best rate',
    financing: (rate: string, day: string) => `Cost of paying on day ${day}, ${rate} a year`,
    net: 'Net gain',
    bridgeNote: (n: number) => `${n} suppliers. Financing is charged only on lines that had no Skonto; lines with a lower Skonto gain the difference in rate.`,
    index: 'Price index of the flagged articles, 2024 = 100',
    indexArticles: 'Flagged articles, weighted with this period\'s volumes',
    indexPath: (rate: string) => `Annahme: index path at ${rate} a year`,
    indexNote: 'The path is an assumption, not a sourced index. Everything above it is Kostenvermeidung, not a saving.',
    year: 'Year',
    comparison: 'Largest gaps: preferred supplier against the cheapest supplier of the same article',
    preferred: 'Vorzugslieferant',
    cheapest: 'Günstigster Lieferant',
    share: 'Volume share',
    onTime: 'On time',
    cheaper: (pct: string) => `${pct} günstiger`,
    gapOn: (gap: string, volume: string) => `${gap} on ${volume} pieces at the preferred supplier`,
    noRun: 'Run the agent for this period to see its chart.',
  },
  // External Price Benchmark, the flagship preview agent (spec mvp-price-benchmark). Wording: potential, indicative, to be validated.
  benchmark: {
    flagship: 'Flagship',
    inDevelopment: 'In development',
    moonshot: 'Moonshot',
    lowConfidence: 'Low confidence',
    devTitle: 'This agent is very much in development.',
    devMore: 'What is built and what is missing',
    devText: 'This page shows the idea end to end on a small, hand-picked sample: for 4 of 5,077 articles an LLM guessed the real part and researched public prices. The mechanism works; coverage, matching quality and price data are not production grade yet, and running it across all articles needs a trained classifier and licensed price data.',
    headlineLabel: 'Potential savings:',
    headlineRange: (low: string, high: string) => `${low} – ${high} / year`,
    headlineSample: (n: number) => `(sample of ${n} articles)`,
    subline: (n: number, universe: string, date: string) => `${n} of ${universe} articles · parts inferred by an LLM from weight and description · web prices researched on ${date}`,
    disclaimerLead: 'Indicative only. Verify before taking action.',
    disclaimerMore: 'What that means',
    disclaimer: "MechaForm's master data has no manufacturer part numbers. The parts below were inferred by an LLM from description, weight and price level for a hand-picked sample of 4 articles. Benchmarks are public webshop or list prices, not negotiated industrial prices. Specs (e.g. print, grade, variant) may differ. Every figure needs to be validated through a spec check and an RFQ.",
    methodTitle: 'How the scan works, and how it scales',
    today: 'Today (sample)',
    atScale: 'At scale',
    steps: [
      { title: 'Identify the part', today: 'An LLM guessed the manufacturer part number or spec from description, net weight, price level and volume. Its output is stored with the sample.', scale: 'A classifier trained on confirmed matches: description, weight and CN code to eCl@ss class to MPN candidates.' },
      { title: 'Find comparable offers', today: 'An LLM researched public prices for the part and its equivalents and listed the suppliers with links, dated 2026-09-15.', scale: 'Distributor APIs (Mouser, Digi-Key, Farnell) and catalogues wherever MPNs exist; refreshed automatically.' },
      { title: 'Compare and size', today: "Every run recomputes MechaForm's price per supplier from the live orders and sizes the gap as a low-to-high range, in under a second.", scale: 'The same rule on every matched article, re-run with each order and price update.' },
      { title: 'Validate and act', today: 'Spec check first, then an RFQ that includes the benchmark sources.', scale: 'Human confirmation of the match, then RFQ and framework contract.' },
    ],
    scaleNote: 'The sample proves the mechanism, not the coverage. At scale the hard parts are the part matching and trustworthy price data.',
    scanTitle: 'Scan results',
    scanSub: (n: number, universe: string, when: string) => `${n} of ${universe} articles matched in this run · ${when}`,
    scanNote: 'A match is an article the agent believes it identified. Run the scan again after new orders; the rest of the catalogue needs the trained classifier.',
    runScan: 'Run scan',
    article: (no: number, category: string) => `Article ${no} · ${category}`,
    recommendation: 'Recommendation',
    reco: {
      supplier_change: (part: string, target: string, paid: string) => `Re-source ${part}: comparable parts go for about ${target}, MechaForm pays ${paid}.`,
      brand_substitution: (part: string, target: string, paid: string) => `Test a second-tier brand for ${part}: about ${target} against ${paid} today, decided on cost per part.`,
      price_confirmed: (pct: string) => `Keep the supplier: MechaForm pays ${pct} below the list price, a normal OEM discount.`,
    } as Record<string, (...a: string[]) => string>,
    nextStep: 'Next step',
    pathForward: (n: number) => `Path forward (${n} steps)`,
    evidence: 'Evidence and details',
    webShowed: 'What the web showed',
    priceLine: (paid: string, target: string, pct: string) => `MechaForm pays ${paid} · our target ${target} after a haircut for the unknown spec · ${pct} above`,
    priceLineConfirmed: (paid: string, list: string) => `MechaForm pays ${paid} against a list price of ${list}`,
    noSavingsLine: 'No savings case, the price is confirmed',
    identifiedAs: 'Identified as',
    guess: 'Guess',
    idType: { mpn_guess: 'MPN guess', spec_level: 'Spec level', iso_code_geometry: 'ISO code geometry' } as Record<string, string>,
    alternatives: (n: number) => `Alternatives (${n})`,
    identification: 'Identification',
    comparability: 'Price comparability',
    caseType: { supplier_change: 'Change supplier', brand_substitution: 'Brand substitution', price_confirmed: 'Price confirmed' } as Record<string, string>,
    mechaform: 'MechaForm 2026',
    compare: 'Price comparison',
    target: 'Benchmark-based target',
    list: 'Benchmark list price',
    gap: (pct: string) => `${pct} above the benchmark-based target`,
    below: (pct: string) => `MechaForm pays ${pct} below list`,
    webPrice: 'Web price',
    source: 'Source',
    retrieved: (date: string) => `retrieved ${date}`,
    savingsLabel: 'Potential savings / year',
    savingsCases: (low: string, high: string) => `Low case at ${low}, high case at ${high}`,
    noSavings: 'No savings case',
    confirmedNote: 'The agent also confirms fair prices: keep the benchmark as evidence in the next negotiation.',
    suppliers: 'Suppliers 2026',
    actions: 'Recommended actions',
    notRun: 'Run the agent for this period to compute MechaForm\'s 2026 prices for the sample articles.',
    previewText: "Finds the real part behind an article and compares MechaForm's price with public web prices. Sample of 4 of 5,077 articles.",
    previewValue: (low: string, high: string) => `Indicative on the sample: ${low} – ${high} / year, not in any total`,
    previewOpen: 'Open the flagship',
    headlineNote: 'potentially a lot',
    headlineNoteTail: 'Not counted: in development, sample of 4 articles.',
    runLog: 'Range, low confidence',
    navMark: 'Flagship',
    cardText: "Finds the real part behind an article, then cheaper external suppliers for it, and sizes the saving from MechaForm's own orders.",
    cardValue: (low: string, high: string) => `${low} – ${high} / year`,
    cardSample: (n: number) => `Potential, on a sample of ${n} articles`,
    cardRun: (when: string, n: number) => `Last run ${when} · ${n} sample articles · not in any total`,
    cardNotRun: 'Not run for this period yet. Run it to size the sample from the live orders.',
    cardPipeline: ['LLM guesses the part', 'LLM finds cheaper suppliers', 'Compare with our orders', 'Spec check and RFQ'],
    run: 'Run',
    open: 'Open the flagship',
  },
  period: { label: 'Period', custom: 'Custom range', from: 'From', to: 'To', apply: 'Apply' },
  feed: { title: 'Agent activity', none: 'No activity yet. Run an agent.' },
  status: { open: 'OFFEN', draft_ready: 'ENTWURF', in_progress: 'IN BEARBEITUNG', sent_simulated: 'GESENDET (SIMULIERT)', realised: 'REALISIERT', dismissed: 'VERWORFEN' } as Record<string, string>,
  // Recommendation card: German labels as in the brief (decision 2026-09-15); numbers keep the app's English format.
  reco: {
    title: 'Empfehlung',
    internal: 'Intern',
    external: 'Extern',
    createTask: 'Aufgabe anlegen',
    taskCreated: (due: string) => `Aufgabe angelegt, fällig ${due}`,
    createDraft: 'Entwurf erstellen',
    draftNote: 'Entwurf, vor dem Versand prüfen',
    sequence: { internal_first: 'ERST INTERN', external_first: 'ERST EXTERN', internal_only: 'NUR INTERN' } as Record<string, string>,
    roleNote: 'Rolle, keine Person',
    responsible: 'Vertragsverantwortlich',
    buyer: (id: string) => `Einkäufer ${id}`,
    category: (id: string) => `Kategorieeinkauf, Einkaufsorg. ${id}`,
    empty: 'Für diese Feststellung liegt noch keine Empfehlung vor. Den Agenten erneut ausführen, um sie zu erzeugen.',
    tasksError: 'Aufgaben konnten nicht geladen werden.',
    taskError: 'Aufgabe wurde nicht angelegt:',
    column: 'Empfehlung',
  },
  // Scenario card (spec mvp-agent-scenarios): Tacto's "Vorgeschlagene Szenarien", German like the recommendation card.
  scenarios: {
    title: 'Vorgeschlagene Szenarien',
    how: { draft: 'ENTWURF', task: 'AUFGABE', negotiation: 'VERHANDLUNG', idea: 'IDEE' } as Record<string, string>,
    sample: 'BEISPIELINDEX',
    createDraft: 'Entwurf erstellen',
    createTask: 'Aufgabe anlegen',
    negotiate: 'Verhandlungsvorbereitung beginnen',
    taskCreated: 'Aufgabe angelegt',
    ideaNote: 'Idee, noch ohne Aktion im Prototyp',
    noDraft: 'Für diese Feststellung ist kein Lieferantenentwurf vorgesehen.',
    empty: 'Der Agent hat für diese Feststellung keine Szenarien. Den Agenten erneut ausführen, um sie zu erzeugen.',
    error: 'Szenarien konnten nicht geladen werden.',
    taskError: 'Aufgabe wurde nicht angelegt:',
  },
  finding: { markSent: 'Als gesendet markieren (Simulation)', dismiss: 'Verwerfen', reopen: 'Wieder öffnen', linesChecked: 'lines checked', flagged: 'flagged' },
  draft: {
    open: 'Aktion entwerfen',
    header: 'Entwurf, vor dem Versand prüfen',
    madeFrom: (n: number, contract: string | null) => `Erstellt aus ${n} Bestellpositionen${contract ? ` und Vertrag ${contract}` : ''}`,
    numbersLine: 'Alle Zahlen stammen aus Ihren Bestelldaten. Keine neuen Zahlen hinzugefügt.',
    redo: 'Neu entwerfen',
    cfo: 'Als CFO-Erläuterung',
    budget: 'Budget für Entwürfe erschöpft, gespeicherte Entwürfe verfügbar',
    missingKey: 'Kein API-Schlüssel hinterlegt. Gespeicherte Entwürfe werden angezeigt, neue können nicht erstellt werden.',
    empty: 'Noch kein Entwurf. Aktion entwerfen erstellt ihn aus den Bestellpositionen dieser Feststellung.',
    rejected: 'Der Entwurf hat die Prüfung nicht bestanden und wurde verworfen.',
    refused: 'Kein Entwurf: ',
    numbers: 'Verwendete Zahlen',
    evidence: 'Belege',
    cached: 'Gespeicherter Entwurf',
    subject: 'Betreff',
  },
  runs: { title: 'Run log', none: 'No runs yet.' },
  // Negotiation trainer (preview, English by decision 2026-09-16)
  trainer: {
    nav: 'Negotiation trainer',
    title: 'Negotiation trainer',
    preview: 'Preview',
    subtitle: (supplier: string) => `Practise a negotiation with ${supplier} on MechaForm's own 2026 data. A language model plays the supplier's key account manager and a coach; every number it may use comes from the brief.`,
    roadmap: 'Roadmap',
    stages: [
      { when: 'Preview, today', what: 'Stored practice session and one live turn' },
      { when: 'Next', what: 'Practice on your own supplier data and targets' },
      { when: 'Later', what: 'Prepare real negotiations in the negotiation cockpit' },
    ],
    brief: 'Supplier brief',
    briefNote: 'Built by the rules from the register, calendar 2026. The model may only use these numbers.',
    session: 'Stored practice session',
    you: 'You, buyer',
    supplierRole: (supplier: string) => `${supplier}, key account manager`,
    coach: 'Coach',
    nextFact: 'Use next',
    concession: { none: 'No concession', partial: 'Partial concession', full: 'Full concession' } as Record<string, string>,
    assessment: { strong: 'Strong', ok: 'OK', weak: 'Weak' } as Record<string, string>,
    nextTurn: 'Next turn',
    showAll: 'Show all turns',
    replayHint: (n: number) => `The stored session has ${n} turns. Press Next turn to replay them one by one; no model is called.`,
    turnOf: (n: number, of: number) => `Turn ${n} of ${of}`,
    liveLabel: 'Your next message',
    livePlaceholder: 'Answer the supplier. Use a fact from the brief with its number and ask for a concrete outcome.',
    send: 'Send',
    liveTurn: 'Live turn',
    locked: 'Preview: one live turn per session.',
    liveTurnsUsed: 'This practice chat is full.',
    startOver: 'Start over',
    rejected: 'The reply did not pass the checks and was not stored:',
    budget: 'The model budget for the demo is used up. The stored session still replays.',
    missingKey: 'No API key is set. The stored session still replays; live turns are off.',
    failed: 'The live turn failed:',
    empty: 'No stored session yet. Seed it with node scripts/trainer-seed.mjs.',
    chooseTitle: 'Recommended negotiations',
    whyTitle: 'Why renegotiate',
    searchTitle: 'Or target a supplier',
    searchLabel: 'Supplier name',
    searchPlaceholder: 'Search all suppliers of the period',
    searchEmpty: 'No supplier of this period matches.',
    searchHit: (spend: string, years: number) => `${spend} in the period, ${years} years of orders`,
    suggested: 'Suggested opening, from the supplier\'s own numbers. Edit before you send.',
    chooseNote: 'Suppliers whose prices run furthest above the cost index basket where nothing is agreed yet: no framework contract, no price tiers, no Skonto on these articles. Index Guard runs on sample index data.',
    aboveBasket: (pct: string) => `${pct} above the cost basket`,
    openSpend: (spend: string, n: number) => `${spend} on ${n} ${n === 1 ? 'article' : 'articles'} without an agreement`,
    gapLabel: 'Gap in the period',
    startWith: (name: string) => `Negotiate with ${name}`,
    exampleTitle: 'Or replay the stored example',
    exampleNote: (name: string) => `Five stored turns with ${name}, the supplier with the contract and Skonto cases. No model call.`,
    back: 'Back to the cases',
    history: 'What we know',
    supplies: 'Supplies',
    spendLabel: 'Spend in the period',
    sinceLabel: 'First order',
    deliveryLabel: 'On time',
    buyersLabel: 'Ordered by',
    statusLabel: 'Supplier status',
    siteLabel: 'Website',
    assumptions: 'Not in the data',
    assumptionsText: 'The export carries no relationship rating, no record of past negotiations and no contact person. Treat the tone of the conversation as practice, not as history.',
    chat: 'Practice chat',
    typing: (supplier: string) => `${supplier} is answering`,
    chatNote: (n: number) => `The model answers as the supplier and coaches you, at most ${n} turns per session.`,
    chatEmpty: 'Open with your first message. Use a fact from the brief with its number and ask for a concrete outcome.',
    turnsLeft: (n: number) => `${n} turns left`,
    startOverConfirm: 'Clear this practice conversation and open a fresh one? The stored example session stays as it is.',
    startOverYes: 'Yes, clear it',
    startOverCancel: 'Keep it',
    lockedChat: 'This practice chat is full. Start over for a fresh one.',
  },
  register: {
    title: 'Register',
    subtitle: 'Every finding of the latest runs for the period, with who has to act. Filter by recipient to see what lands on one role.',
    filterLabel: 'Recipient',
    all: 'All recipients',
    empty: 'No findings for this period yet. Run the agents to fill the register.',
    emptyRole: (role: string) => `No finding in this period lands on ${role}.`,
    runAll: 'Run all agents for this period',
    agent: 'Agent',
    finding: 'Finding',
  },
  table: {
    order: 'Order',
    date: 'Date',
    article: 'Article',
    supplier: 'Supplier',
    quantity: 'Quantity',
    paid: 'Paid',
    contractPrice: 'Contract price',
    tierPrice: 'Tier price',
    tierReached: 'Tier reached',
    baseline: 'Weighted price',
    target: 'Target',
    gap: 'Gap 2026',
    volume: 'Volume 2026',
  },
} as const
