// Every user-facing string lives here. Sentence case. No em dashes, no exclamation marks, no emoji.
export const copy = {
  brand: 'tacto',
  productName: 'Procurement cockpit',
  customer: 'MechaForm GmbH',
  cockpit: {
    title: 'Savings agents',
    subtitle: 'Identified in the 2026 order history. Values are volume times price gap, one primary case per article.',
    headlineLabel: 'Identified by enabled agents',
    keptApart: 'Kept apart, not savings',
    contractCliff: 'Spend that loses its contract ceiling on 2026-12-31',
    blockedSpend: 'Orders to blocked or phased-out suppliers',
    lastRun: 'Last run',
    notRun: 'Not run for this period',
    runAll: 'Run all agents',
    running: 'Running',
    gross: 'Gross sum of enabled agents',
    dedup: 'One primary case per article, plus terms',
    explain: (name: string) => `Explain ${name}`,
    confidence: (value: string) => `Confidence ${value}, a human judgement of survival after supplier contact`,
    rows: 'flagged rows',
    open: 'Open agent',
    empty: 'No agents enabled. Set VITE_ENABLED_AGENTS to a comma-separated list of case keys.',
    error: 'The database did not answer. Check the Supabase URL and anon key in the environment.',
    loading: 'Loading agents',
  },
  agent: {
    rule: 'Rule',
    evidence: 'Evidence required',
    calculation: 'Calculation',
    action: 'Customer action',
    trigger: 'Trigger',
    register: 'Flagged rows',
    total: 'Total',
    evidenceDrawer: 'Order lines 2026',
    referenced: 'Referenced',
    unreferenced: 'No reference',
    close: 'Close',
    page: (n: number, of: number) => `Page ${n} of ${of}`,
    previous: 'Previous',
    next: 'Next',
    perOrder: 'Per order',
    annualVolume: 'Annual volume at top tier',
    yearChart: 'Share of eligible order lines priced above the recorded tier',
    workedExample: 'Worked example',
    run: 'Run agent',
    how: 'How this agent works',
    howClose: 'Hide explanation',
    trend: 'Gap by month',
    findings: 'Findings',
    noRun: 'This agent has not run for the selected period. Run it to see findings.',
  },
  period: { label: 'Period', custom: 'Custom range', from: 'From', to: 'To', apply: 'Apply' },
  feed: { title: 'Agent activity', none: 'No activity yet. Run an agent.' },
  status: { open: 'OFFEN', draft_ready: 'ENTWURF', sent_simulated: 'GESENDET (SIMULIERT)', realised: 'REALISIERT', dismissed: 'VERWORFEN' } as Record<string, string>,
  finding: { markSent: 'Als gesendet markieren (Simulation)', dismiss: 'Verwerfen', reopen: 'Wieder öffnen', linesChecked: 'lines checked', flagged: 'flagged' },
  runs: { title: 'Run log', none: 'No runs yet.' },
  table: {
    order: 'Order',
    date: 'Date',
    article: 'Article',
    supplier: 'Supplier',
    quantity: 'Quantity',
    paid: 'Paid',
    contractPrice: 'Contract price',
    tierPrice: 'Tier price',
    tierReached: 'Tier reached',
    baseline: 'Weighted price',
    target: 'Target',
    gap: 'Gap 2026',
    volume: 'Volume 2026',
  },
} as const
