// Every user-facing string lives here. Sentence case. No em dashes, no exclamation marks, no emoji.
export const copy = {
  brand: 'tacto',
  productName: 'Procurement cockpit',
  customer: 'MechaForm GmbH',
  cockpit: {
    title: 'Savings agents',
    subtitle: 'Identified in the 2026 order history. Values are volume times price gap, one primary case per article.',
    headlineLabel: 'Identified by enabled agents',
    keptApart: 'Kept apart, not savings',
    contractCliff: 'Spend that loses its contract ceiling on 2026-12-31',
    blockedSpend: 'Orders to blocked or phased-out suppliers',
    lastRun: 'Last run',
    notRun: 'Not run for this period',
    runAll: 'Run all agents',
    running: 'Running',
    gross: 'Gross sum of enabled agents',
    dedup: 'One primary case per article, plus terms',
    explain: (name: string) => `Explain ${name}`,
    confidence: (value: string) => `Confidence ${value}, a human judgement of survival after supplier contact`,
    rows: 'flagged rows',
    open: 'Open agent',
    empty: 'No agents enabled. Set VITE_ENABLED_AGENTS to a comma-separated list of case keys.',
    error: 'The database did not answer. Check the Supabase URL and anon key in the environment.',
    loading: 'Loading agents',
  },
  agent: {
    rule: 'Rule',
    evidence: 'Evidence required',
    calculation: 'Calculation',
    action: 'Customer action',
    trigger: 'Trigger',
    register: 'Flagged rows',
    total: 'Total',
    evidenceDrawer: 'Order lines 2026',
    referenced: 'Referenced',
    unreferenced: 'No reference',
    close: 'Close',
    page: (n: number, of: number) => `Page ${n} of ${of}`,
    previous: 'Previous',
    next: 'Next',
    perOrder: 'Per order',
    annualVolume: 'Annual volume at top tier',
    yearChart: 'Share of eligible order lines priced above the recorded tier',
    workedExample: 'Worked example',
    run: 'Run agent',
    how: 'How this agent works',
    howClose: 'Hide explanation',
    trend: 'Gap by month',
    findings: 'Findings',
    noRun: 'This agent has not run for the selected period. Run it to see findings.',
  },
  period: { label: 'Period', custom: 'Custom range', from: 'From', to: 'To', apply: 'Apply' },
  feed: { title: 'Agent activity', none: 'No activity yet. Run an agent.' },
  status: { open: 'OFFEN', draft_ready: 'ENTWURF', in_progress: 'IN BEARBEITUNG', sent_simulated: 'GESENDET (SIMULIERT)', realised: 'REALISIERT', dismissed: 'VERWORFEN' } as Record<string, string>,
  // Recommendation card: German labels as in the brief (decision 2026-09-15); numbers keep the app's English format.
  reco: {
    title: 'Empfehlung',
    internal: 'Intern',
    external: 'Extern',
    createTask: 'Aufgabe anlegen',
    taskCreated: (due: string) => `Aufgabe angelegt, fällig ${due}`,
    createDraft: 'Entwurf erstellen',
    draftNote: 'Entwurf, vor dem Versand prüfen',
    sequence: { internal_first: 'ERST INTERN', external_first: 'ERST EXTERN', internal_only: 'NUR INTERN' } as Record<string, string>,
    roleNote: 'Rolle, keine Person',
    buyer: (id: string) => `Einkäufer ${id}`,
    category: (id: string) => `Kategorieeinkauf, Einkaufsorg. ${id}`,
    empty: 'Für diese Feststellung liegt noch keine Empfehlung vor. Den Agenten erneut ausführen, um sie zu erzeugen.',
    tasksError: 'Aufgaben konnten nicht geladen werden.',
    taskError: 'Aufgabe wurde nicht angelegt:',
    column: 'Empfehlung',
  },
  finding: { markSent: 'Als gesendet markieren (Simulation)', dismiss: 'Verwerfen', reopen: 'Wieder öffnen', linesChecked: 'lines checked', flagged: 'flagged' },
  draft: {
    open: 'Aktion entwerfen',
    header: 'Entwurf, vor dem Versand prüfen',
    madeFrom: (n: number, contract: string | null) => `Erstellt aus ${n} Bestellpositionen${contract ? ` und Vertrag ${contract}` : ''}`,
    numbersLine: 'Alle Zahlen stammen aus Ihren Bestelldaten. Keine neuen Zahlen hinzugefügt.',
    redo: 'Neu entwerfen',
    cfo: 'Als CFO-Erläuterung',
    budget: 'Budget für Entwürfe erschöpft, gespeicherte Entwürfe verfügbar',
    missingKey: 'Kein API-Schlüssel hinterlegt. Gespeicherte Entwürfe werden angezeigt, neue können nicht erstellt werden.',
    empty: 'Noch kein Entwurf. Aktion entwerfen erstellt ihn aus den Bestellpositionen dieser Feststellung.',
    rejected: 'Der Entwurf hat die Prüfung nicht bestanden und wurde verworfen.',
    refused: 'Kein Entwurf: ',
    numbers: 'Verwendete Zahlen',
    evidence: 'Belege',
    cached: 'Gespeicherter Entwurf',
    subject: 'Betreff',
  },
  runs: { title: 'Run log', none: 'No runs yet.' },
  register: {
    title: 'Register',
    subtitle: 'Every finding of the latest runs for the period, with who has to act. Filter by recipient to see what lands on one role.',
    filterLabel: 'Recipient',
    all: 'All recipients',
    empty: 'No findings for this period yet. Run the agents to fill the register.',
    emptyRole: (role: string) => `No finding in this period lands on ${role}.`,
    runAll: 'Run all agents for this period',
    agent: 'Agent',
    finding: 'Finding',
  },
  table: {
    order: 'Order',
    date: 'Date',
    article: 'Article',
    supplier: 'Supplier',
    quantity: 'Quantity',
    paid: 'Paid',
    contractPrice: 'Contract price',
    tierPrice: 'Tier price',
    tierReached: 'Tier reached',
    baseline: 'Weighted price',
    target: 'Target',
    gap: 'Gap 2026',
    volume: 'Volume 2026',
  },
} as const
